package top.bbykl.crm.setting.mapper;

import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;
import top.bbykl.crm.setting.model.User;

import java.util.List;
import java.util.Map;

@Mapper
@Repository
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Mon Nov 07 16:33:25 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Mon Nov 07 16:33:25 CST 2022
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Mon Nov 07 16:33:25 CST 2022
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Mon Nov 07 16:33:25 CST 2022
     */
    User selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Mon Nov 07 16:33:25 CST 2022
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_user
     *
     * @mbggenerated Mon Nov 07 16:33:25 CST 2022
     */
    int updateByPrimaryKey(User record);



    /**
     * @description: 根据用户名和密码来查询用户
     * @param: map封装前端传来参数
 * @param map
     * @return: 实体用户类
 * @return user
     * @author 盛祥进
     * @date: 2022/11/9 12:23
     */
    //注意此处位置mapper.xml文件无效，更改sql还需在resource下进行
    User selectUserByPassword(Map<String,Object> map);
    List<User> selectAllUser();
}